# ==============================================================================
# Conduit / LobeHub Android R8 & ProGuard Obfuscation Rules
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. Native Methods & JNI Bindings (SQLite, Drift, FFI)
# ------------------------------------------------------------------------------
# Preserve all JNI native method entry points and signatures
-keepclasseswithmembernames class * {
    native <methods>;
}

# Drift SQLite native bindings (sqlite3_flutter_libs, drift, requery, org.sqlite)
-keep class com.simonbinder.sqlite3.** { *; }
-keep interface com.simonbinder.sqlite3.** { *; }
-keepclassmembers class com.simonbinder.sqlite3.** { *; }
-dontwarn com.simonbinder.sqlite3.**

-keep class io.requery.android.database.sqlite.** { *; }
-keep interface io.requery.android.database.sqlite.** { *; }
-keepclassmembers class io.requery.android.database.sqlite.** { *; }
-dontwarn io.requery.android.database.sqlite.**

-keep class org.sqlite.** { *; }
-keep interface org.sqlite.** { *; }
-keepclassmembers class org.sqlite.** { *; }
-dontwarn org.sqlite.**

# Common Android SQLite helper constructors
-keepclassmembers class * extends android.database.sqlite.SQLiteOpenHelper {
    public <init>(...);
}

# ------------------------------------------------------------------------------
# 2. Networking: Dio, OkHttp3, Okio, and WebSockets
# ------------------------------------------------------------------------------
# Dio & diozero bindings
-keep class com.diozero.** { *; }
-dontwarn com.diozero.**

# OkHttp3 core, interfaces, and reflection points
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**

# OkHttp PublicSuffixDatabase rule resolution via resources
-keepclassmembers class okhttp3.internal.publicsuffix.PublicSuffixDatabase {
    public java.lang.String findMatchingRule(java.lang.String[]);
}

# Okio buffers, byte strings, and segment pools
-keep class okio.** { *; }
-keep interface okio.** { *; }
-dontwarn okio.**

# Java-WebSocket networking
-keep class org.java_websocket.** { *; }
-dontwarn org.java_websocket.**

# ------------------------------------------------------------------------------
# 3. Flutter Plugins & Secure Storage
# ------------------------------------------------------------------------------
# Flutter engine, plugins, and channel registrant
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-dontwarn io.flutter.embedding.**

# Flutter Secure Storage (Android KeyStore, SharedPreferences & crypto ciphers)
-keep class com.it_nomads.fluttersecurestorage.** { *; }
-keep interface com.it_nomads.fluttersecurestorage.** { *; }
-keepclassmembers class com.it_nomads.fluttersecurestorage.** { *; }
-dontwarn com.it_nomads.fluttersecurestorage.**

# Security providers and crypto reflection
-keep class javax.crypto.** { *; }
-keepclassmembers class * extends java.security.Provider {
    public <init>(...);
}

# App platform channel classes, Pigeon autogenerated APIs & native bridges
-keep class app.cogwheel.conduit.** { *; }
-keepclassmembers class app.cogwheel.conduit.** { *; }

# Flutter CallKit Incoming plugin
-keep class com.hiennv.flutter_callkit_incoming.** { *; }
-dontwarn com.hiennv.flutter_callkit_incoming.**

# ------------------------------------------------------------------------------
# 4. JSON Reflection, Serialization & Enums
# ------------------------------------------------------------------------------
# Preserve reflection metadata: annotations, enclosing methods, generic signatures, line numbers
-keepattributes *Annotation*,EnclosingMethod,InnerClasses,Signature,SourceFile,LineNumberTable

# Preserve enum lookup methods required by JSON/serialization converters
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# Keep Unsafe access if needed by serializers
-keep class sun.misc.Unsafe { *; }

# Gson serialization streams and annotations
-keep class com.google.gson.stream.** { *; }
-keepclassmembers class * {
    @com.google.gson.annotations.SerializedName <fields>;
    @com.google.gson.annotations.Expose <fields>;
}

# Standard Java serializable classes
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

# org.json (used in testing and model validation)
-keep class org.json.** { *; }
-dontwarn org.json.**

# ------------------------------------------------------------------------------
# 5. Kotlin Coroutines & Background Workers
# ------------------------------------------------------------------------------
-keepclassmembers class kotlinx.coroutines.** {
    volatile <fields>;
}
-dontwarn kotlinx.coroutines.**

